FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang make

COPY . /lzsa
WORKDIR /lzsa
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /lzsa/lzsa /
